baseURL = 'https://jamesfell.github.io/'
languageCode = 'en-au'
title = 'code'
theme = 'paper'
description = 'Useful tools for research, and helping build better evidence bases.'

[params]
  github = 'jamesfell0000'
  researchgate = 'James-Fell-5'
  twitter = 'jamesfell0000'
  threads = 'jamesfell0000'
  rss = true
  
  #misc
  monoDarkIcon = true