baseURL = 'https://jamesfell.github.io/'
languageCode = 'en-au'
title = 'code'
theme = 'paper'
description = 'Useful tools for research, and helping build better evidence bases.'

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons. Customise the social list in baseof.html and add custom treatment in header.html
  github = 'jamesfell0000'
  researchgate = 'https://www.researchgate.net/profile/James-Fell-5'
  twitter = 'jamesfell0000'
  threads = 'https://www.threads.net/@jamesfell0000'
  rss = true
  
  
  #misc
  monoDarkIcon = true