baseURL = 'https://jamesfell.github.io/'
languageCode = 'en-au'
title = 'code'
theme = 'PaperMod'
description = 'Useful tools for research, and helping build better evidence bases.'
[[socialIcons]]
name = "researchgate"
url = "https://www.researchgate.net/profile/James-Fell-5"

[[socialIcons]]
name = "twitter"
url = "https://www.twitter.com/jamesfell0000"