baseURL = 'https://jamesfell.github.io/'
languageCode = 'en-au'
title = 'code'
theme = 'paper'
description = 'Useful tools for research, and helping build better evidence bases.'

[params]
  twitter = 'jamesfell0000'