baseURL = 'https://jamesfell.github.io/'
languageCode = 'en-au'
title = 'code'
theme = 'paper'
description = 'Useful tools for research, and helping build better evidence bases.'

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # home page profile
  avatar = 'https://upload.wikimedia.org/wikipedia/commons/0/04/Font_Awesome_5_solid_laptop-code.svg'
  name = 'code'
  bio = 'Sharing tools to support evidence base development'

  # header social icons. Customise the social list in baseof.html and add custom treatment in header.html
  github = 'jamesfell0000'
  researchgate = 'https://www.researchgate.net/profile/James-Fell-5'
  twitter = 'jamesfell0000'
  threads = 'https://www.threads.net/@jamesfell0000'
  rss = false
  
  
  #misc
  monoDarkIcon = true